config/routes.rb
Webshop::Application.routes.draw do  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root "pages#home"

  resources :users

  resources :products do
    collection do
      get :home
    end
  end

  resources :orders do 
    collection do
      get :make_payment
    end
  end

  namespace :admin do
    resources :users
    resources :products
    resources :comments
    resources :orders
  end
end

app/models/order.rb
class Order
  include Mongoid::Document
  include Mongoid::Timestamps

  belongs_to :user
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::BaseController
  def index   
    @orders = Order.all 
  end

  def new 
    @order = Order.new
  end

  def show
    @order = Order.find(params[:id])
  end

  def edit
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    if @order.update_attributes(params[:order])
      redirect_to admin_orders_path, notice: "cap nhap thanh cong"
    else
      render action: "edit", notice: "errors"
    end
  end

  def destroy
    @order = Order.find(params[:id]).destroy
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def make_payment
    if cookies["basket"].nil?
      redirect_to root_path, notice: "Not product on order" 
      return
    end
    # binding.pry
    @items = JSON.parse(cookies["basket"])["items"]
  end
end

app/views/admin/orders/_form.html.erb
   <div class="fieldWithErrors">
    <% @order.errors.full_messages.each do |message| %>
      <div class="error">
        <p><%= message %></p>
      </div>
    <% end -%>
  </div>
  <div class="group">
    <%= f.label :_id, t("activerecord.attributes.order._id", :default => "Id"), :class => :label %>
    <%= f.text_field :_id, :class => 'text_field' %>
    <span class="description">Enter: the ID of Order</span>
  </div>

  <div class="group">
    <%= f.label :user_id, t("activerecord.attributes.order.user_id", :default => "User"), :class => :label %>
    <%= f.text_field :user_id, :class => 'text_field' %>
    <span class="description">Enter: the user id created order</span>
  </div>
        
<div class="group navform wat-cf">
  <button class="button" type="submit">
    <%= image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}") %> <%= t("web-app-theme.save", :default => "Save") %>
  </button>
  <span class="text_button_padding"><%= t("web-app-theme.or", :default => "or") %></span>
	<%= link_to t("web-app-theme.cancel", :default => "Cancel"), admin_orders_path, :class => "text_button_padding link_button" %>
</div>

app/views/admin/orders/_sidebar.html.erb
<div class="block notice">
  <h3>Simple Block</h3>
  <div class="content">
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
  </div>
</div>
<div class="block">
  <h3>Links</h3>
  <ul class="navigation">
    <li><a href="#">Link 1</a></li>
    <li><a href="#">Link 2</a></li>
  </ul>
</div>

app/views/admin/orders/edit.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first">
        <%= link_to "#{t("web-app-theme.list", :default => "List")}", admin_orders_path  %>
      </li>
      <li>
        <%= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_order_path %>
      </li>
      <li class="active">
        <%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_admin_order_path %>
      </li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.edit", :default => "Edit") %> Order</h2>
    <div class="inner">
      <%= form_for @order, :url => admin_order_path(@order), :html => { :class => :form } do |f| -%>
      <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/admin/orders/index.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first active"><%= link_to "#{t("web-app-theme.list", :default => "List")}", admin_orders_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_order_path %></li>
    </ul>
  </div>          
  <div class="content">          
    <h2 class="title"><%= t("web-app-theme.all", :default => "All")  %> Orders</h2>
    <div class="inner">
      <table class="table">
        <tr>             
          <th class="first">ID</th>
          <th>
            <%= t("activerecord.attributes.admin_order._id", :default => t("activerecord.labels._id", :default => "_id")) %>
          </th>
          <th>
            <%= t("web-app-theme.created_at", :default => "Created at")  %>
          </th>
          <th class="last">&nbsp;</th>
        </tr>
        <% @orders.each do |order| -%>
        <tr class="<%= cycle("odd", "even") %>">
          <td>
            <%= order.id %>
          </td>
          <td>
            <%= link_to order._id, admin_order_path(order) %>
          </td>
          <td>
            <%= order.created_at %>
          </td>
          <td class="last">
            <%= link_to "#{t("web-app-theme.show", :default => "Show")}", admin_order_path(order) %> |
            <%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_admin_order_path(order) %>|
            <%= link_to "#{t("web-app-theme.delete", :default => "Delete")}", admin_order_path(order), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
          </td>
        </tr>          
        <% end -%>
      </table>
      <div class="actions-bar wat-cf">
        <div class="actions">
        </div>       
      </div>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/admin/orders/new.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first">
        <%= link_to "#{t("web-app-theme.list", :default => "List")}", admin_orders_path  %>
      </li>
      <li class="active">
        <%= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_order_path %>
      </li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.new", :default => "New")%>  Order</h2>
    <div class="inner">
      <%= form_for :order, :url => admin_orders_path, :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/admin/orders/show.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", admin_orders_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_order_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.show", :default => "Show")}", admin_order_path %></li>
    </ul>
  </div>          
  <div class="content">
    <div class="inner">    
        <p>
          <b><%= t("activerecord.attributes.admin_order._id", :default => t("activerecord.labels._id", :default => "")) %>:</b>
          <%= @order._id %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.admin_order.user_id", :default => t("activerecord.labels.user_id", :default => "User")) %>:</b>
          <%= @order.user_id %>
        </p>
      <div class="wat-cf">
        <%= link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_admin_order_path(@order), :class => "button" %> 
        <%= link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), admin_order_path(@order), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
      </div>      
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>