config/routes.rb
Webshop::Application.routes.draw do  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root "pages#home"

  resources :users

  resources :products do
    collection do
      get :home
    end
  end

  resources :orders do 
    collection do
      get :make_payment
    end
  end

  namespace :admin do
    resources :users
    resources :products
    resources :comments
    resources :orders
  end
end

app/models/product.rb
class Product
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, type: String
  field :description, type: String
  field :price, type: Float
  field :categories, type: Array

  validates :name, presence: true
  validates :price, presence: true, numericality: true

  has_many :product_images, :dependent => :destroy
  accepts_nested_attributes_for :product_images, :reject_if => lambda { |a| a[:photo].blank? }, allow_destroy: true
  has_many :comments
  has_and_belongs_to_many :line_items 
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController
  def index   
    @products = Product.all 
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
    # binding.pry
    @product = Product.find(params[:id])
    @categories = @product.categories.map{|i| i}.join(",") unless @product.categories.nil?
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    flash[:success] = "Produt delete."
    redirect_to admin_products_path
  end

  def new 
    @product = Product.new
    3.times { @product.product_images.build }
  end

  def create
    params[:product][:categories] = params[:product][:categories].split(", ")
    @product = Product.new(params[:product])
    if @product.save
      redirect_to admin_product_path(@product), notice: "Create success #{@product.name}"
    else
      render 'new', notice: "Product not created"
    end
  end

  def update
    params[:product][:categories] = params[:product][:categories].split(",")
    @product = Product.find(params[:id])
    #binding.pry
    if @product.update_attributes(params[:product])

      redirect_to admin_product_path(@product), notice: "Update success #{@product.name}"
    else
      render action: "edit"
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  
  def index
    # binding.pry
    @products = Product.all.select{|p| !p.categories.blank? && p.categories.include?(params[:categories]) }
    
  end

  def home
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])    
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.erb
   <div class="fieldWithErrors">
    <% @product.errors.full_messages.each do |message| %>
      <div class="error">
        <p><%= message %></p>
      </div>
    <% end -%>
  </div>
  <div class="group">
    <%= f.label :name, t("activerecord.attributes.product.name", :default => "Name"), :class => :label %>
    <%= f.text_field :name, :class => 'text_field' %>
    <span class="description">Ex: the title of product</span>
  </div>

  <div class="group">
    <%= f.label :categories, t("activerecord.attributes.product.name", :default => "Categories"), :class => :label %>
    <%= f.text_field :categories, :class => 'text_field', value: @categories %>
    <span class="description">Ex: the categories of product</span>
  </div>

  <div class="group">
    <%= f.label :description, t("activerecord.attributes.product.description", :default => "Description"), :class => :label %>
    <%= f.text_area :description, size: "120x12", :class => "tinymce" %>
    <span class="description">Ex: the description of product</span>
  </div>

  <div class="group">
    <%= f.label :price, t("activerecord.attributes.product.price", :default => "Price"), :class => :label %>
    <%= f.text_field :price, :class => 'text_field' %>
    <span class="description">Ex: the price of product</span>
  </div>

  <div class="group">
    <%= f.fields_for :product_images, :html => {:multipart => true} do |builder| %>
    <div class="fields">
      <%= builder.file_field :photo %></br>
      <%= builder.hidden_field :_destroy %>
      <%= link_to_function "remove", "remove_fields(this)" %>
      <%= image_tag builder.object.photo.thumb('100x100').url if builder.object.photo_uid %></br>
    </div>
    <% end -%>

    <%= tinymce %>


  </div>
        
<div class="group navform wat-cf">
  <button class="button" type="submit">
    <%= image_tag("web-app-theme/icons/tick.png", 
        :alt => "#{t("web-app-theme.save", 
        :default => "Save")}") %> 
    <%= t("web-app-theme.save", :default => "Save") %>
  </button>
  <span class="text_button_padding"> or </span>
	<%= link_to t("web-app-theme.view", :default => "View"), product_path(@product), :class => "text_button_padding link_button" %>
  <span class="text_button_padding"> - </span>
  <%= link_to t("web-app-theme.cancel", :default => "Cancel"), admin_products_path, :class => "text_button_padding link_button" %>
</div>

app/views/admin/products/edit.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first">
        <%= link_to "#{t("web-app-theme.list", :default => "List")}", admin_products_path  %>
      </li>
      <li>
        <%= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_product_path %>
      </li>
      <li class="active">
      <%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_admin_product_path %>
      </li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.edit", :default => "Edit") %> Product</h2>
    <div class="inner">
      <%= form_for @product, :url => admin_product_path(@product), :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/admin/products/index.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first active"><%= link_to "#{t("web-app-theme.list", :default => "List")}", admin_products_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_product_path %></li>
    </ul>
  </div>          
  <div class="content">          
    <h2 class="title"><%= t("web-app-theme.all", :default => "All")  %> Products</h2>
    <div class="inner">
      <table class="table">
        <tr>             
          <th class="first">Name</th>
          <th>
            <%= t("web-app-theme.description", :default => "Description")  %>
          </th>
          <th>
            <%= t("activerecord.attributes.admin_product.price", :default => t("activerecord.labels.price", :default => "price")) %>
          </th>
          <th>
            <%= t("web-app-theme.created_at", :default => "Created at")  %>
          </th>
          <th class="last">&nbsp;</th>
        </tr>
        <% @products.each do |product| -%>
        <tr class="<%= cycle("odd", "even") %>">
          <td>
            <%= link_to product.name, product_path(product) %>
          </td>
          <td>
            <%#= link_to product.description, admin_product_path(product) %>
            <%= product.description.html_safe %>
          </td>
          <td>
            <%= product.price %>
          </td>
          <td>
            <%= product.created_at %>
          </td>
          <td class="last">
            <%= link_to "#{t("web-app-theme.show", :default => "Show")}", admin_product_path(product) %> |
            <%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_admin_product_path(product) %> |
            <%= link_to "#{t("web-app-theme.delete", :default => "Delete")}", admin_product_path(product), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
          </td>
        </tr>          
        <% end -%>
      </table>
      <div class="actions-bar wat-cf">
        <div class="actions">
        </div>
        
      </div>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/admin/products/new.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first">
        <%= link_to "#{t("web-app-theme.list", :default => "List")}", admin_products_path  %>
      </li>
      <li class="active">
        <%= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_product_path %>
      </li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.new", :default => "New")%>  Product</h2>
    <div class="inner">
      <%= form_for @product, :url => admin_products_path, :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/admin/products/show.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", admin_products_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_product_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.show", :default => "Show")}", admin_product_path %></li>
    </ul>
  </div>          
  <div class="content">
    <div class="inner">
      
        <p>
          <b><%= t("activerecord.attributes.admin_product._id", :default => t("activerecord.labels._id", :default => "")) %>:</b>
          <%= @product._id %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.admin_product.name", :default => t("activerecord.labels.name", :default => "Name")) %>:</b>
          <%= @product.name %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.admin_product.description", :default => t("activerecord.labels.description", :default => "Description")) %>:</b>
          <%= @product.description.html_safe %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.admin_product.price", :default => t("activerecord.labels.price", :default => "Price")) %>:</b>
          <%= @product.price %>
        </p>

        <table class="table">
          <tr>
            <th>ID</th>
            <th>Content</th>
            <th>Created at</th>
          </tr>
          <% @product.comments.each do |o| -%>
          <tr class="<%= cycle("odd", "even") %>">  
            <td><%= o.id %></td>
            <td><%= o.content %></td>
            <td><%= o.created_at %></td>
          </tr>
          <% end -%>
        </table>
      <div class="wat-cf">
        <%= link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_admin_product_path(@product), :class => "button" %> 
        <%= link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.view", :default=> "View")}") + " " + t("web-app-theme.view", :default=> "View"), product_path(@product), :class => "button" %> 
        <%= link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), admin_product_path(@product), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
      </div>      
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>