config/routes.rb
Webshop::Application.routes.draw do  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root "pages#home"

  resources :users

  resources :products do
    collection do
      get :home
    end
  end

  resources :orders do 
    collection do
      get :make_payment
    end
  end

  namespace :admin do
    resources :users
    resources :products
    resources :comments
    resources :orders
  end
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Web App</title>
  <%= stylesheet_link_tag "web-app-theme/base", "web-app-theme/themes/default/style", "web-app-theme/override", :cache => true %>
  <%= javascript_include_tag "application", :cache => true %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="container">
    <div id="header">
      <h1><a href="/admin/users">Web App</a></h1>
      <div id="user-navigation">
        <ul class="wat-cf">
          <li><a href="/"><%= t("web-app-theme.home", :default => "Home") %></a></li>
          <li><a href="/users/sign_out" class="logout"><%= t("web-app-theme.logout", :default => "Logout") %></a></li>
        </ul>
      </div>
      <div id="main-navigation">
        <ul class="wat-cf"> 
          <li class="<%= controller.controller_path == 'admin/users' ? 'active' : '' %>">
            <a href="<%= admin_users_path %>">Users</a>
          </li>
          <li class="<%= controller.controller_path == 'admin/products' ? 'active' : '' %>">
            <a href="<%= admin_products_path %>">Products</a>
          </li>
          <li class="<%= controller.controller_path == 'admin/comments' ? 'active' : '' %>">
            <a href="<%= admin_comments_path %>">Comments</a>
          </li>
          <li class="<%= controller.controller_path == 'admin/orders' ? 'active' : '' %>">
            <a href="<%= admin_orders_path %>">Orders</a>
          </li>
      </div>
    </div>    
    <div id="wrapper" class="wat-cf">
      <div class="flash">
        <% flash.each do |type, message| -%>
          <div class="message <%= type %>">
            <p><%= message %></p>
          </div>
        <% end -%>
      </div>
      <div id="main">
        <%= yield %>
        <div id="footer">
          <div class="block">
            <p>Copyright &copy; <%= Time.now.year %> Web App.</p>
          </div>      
        </div>
      </div>
      <div id="sidebar">
        <%= yield :sidebar %>
      </div>
    </div>    
  </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Webshop</title>
  <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
</head>
<body
<% if params["controller"] == "pages" && params["action"] == "home" %>
  class="home-page"
<% else %>
  class="<%= params['controller']%> <%= params[:categories] %>"
<% end %>
>
  <div id="page">
    <%= render 'layouts/admin_shared/header' %>
    <div class="flash">
      <% flash.each do |type, message| -%>
        <div class="message <%= type %>">
          <p><%= message %></p>
        </div>
      <% end -%>
    </div>
    <% if params["controller"] == "pages" && params["action"] == "home" %>
      <%= render 'layouts/admin_shared/slide' %>
      <%= render 'layouts/admin_shared/adver' %>
    <% end -%>
    <div id="page-content">
      <div class="main main-content">
        <% if params["controller"] == "pages" && params["action"] == "home" %>
          
        <% else %>
          <%= yield %>
        <% end %>
      </div>  
    </div>
    <%= render 'layouts/admin_shared/footer' %>
  </div>
</body>
</html>